version: '3.8'

services:
#  api:
#    build: ./docker/api
#    ports:
#      - "50051:50051"
#    volumes:
#      - ./data:/data
#    environment:
#      - OWNER_TELEGRAM_ID=${OWNER_TELEGRAM_ID:-}
#      - DB_PATH=/data/fighters.db
#      - AI_SERVICE_URL=http://python-ai:8001
#      - HEMAGON_API_URL=http://hemagon-api:8000
#    depends_on:
#      - python-ai
#      - hemagon-api
#
#  bot:
#    build: ./docker/bot
#    environment:
#      - API_ADDR=api:50051
#      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
#      - OWNER_TELEGRAM_ID=${OWNER_TELEGRAM_ID:-}
#    depends_on:
#      - api

  python-ai:
    build:
      context: .
      dockerfile: ./docker/python/ai-service/Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./tmp/volumes/ai-service/loaded_data:/tmp/hemagon_data
      - ./tmp/volumes/ai-service/db:/tmp/db
    environment:
      - HEMAGON_SCRAPPER_URL=http://hemagon-api:8000
      - AI_SERVICE_DB_PATH=/tmp/db/ai-service.db
    depends_on:
      - hemagon-api

  hemagon-api:
    build:
      context: .
      dockerfile: ./docker/python/hemagon/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./tmp/volumes/ai-service/loaded_data:/tmp/hemagon_data

#  vk-mcp:
#    build: ./docker/python/mcp/vk
#    ports:
#      - "8082:8080"
#    environment:
#      - VK_ACCESS_TOKEN=${VK_ACCESS_TOKEN:-}
#      - VK_GROUP_ID=${VK_GROUP_ID:-}

volumes:
  data:

networks:
  default:
    name: easy-tactics-network